# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8a1963090937c6a42825cd4b327de90f4b3021eef2f88f0407e6fc949be589eb4bb7b7e3d6a2b2897888900928f08de108cd7d0eee2dbc655c00c315bd060d

test:
  secret_key_base: 08bf32b79b705e25cd0f0411b064d7e7b37017a80122364b3e10a6d982ba73e631871c8edd5536347222572b87a1c0ba04ff22c3eef53f34a1b15bd565555b39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
